"""Writes dev/FAIRYTALEQA_STATS.md from the converted FairytaleQA episodes
(``scripts/convert_fairytaleqa.py --out``) -- counts by split/attribute/
explicit-implicit, passage-length distributions, the corpus-wide parse-yield
table (strict-full-tree / usable / cap-hit / grounding-fail, over every
sentence any episode's passage cites), the answer-type (a)-(d) breakdown,
and 10 example Q/A pairs per attribute.

Usage:
    python scripts/build_fairytaleqa_stats.py \\
        --episodes runs/fairytaleqa_episodes.jsonl \\
        --out dev/FAIRYTALEQA_STATS.md
"""

from __future__ import annotations

import argparse
import json
import statistics
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, List

_ROOT = Path(__file__).resolve().parent.parent

_GROUNDING_FAIL_REASONS = (
    "unknown-word", "no-parse", "multiple-parses-unresolved",
    "unsupported-construction", "pronoun-unresolvable",
    "no-relation-extracted", "fragment-skipped",
)


def load_episodes(path: Path) -> List[dict]:
    eps = []
    with path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                eps.append(json.loads(line))
    return eps


def _pct(n: int, total: int) -> str:
    return f"{n / total:.1%}" if total else "n/a"


def build(episodes: List[dict]) -> str:
    n = len(episodes)
    lines: List[str] = []
    lines.append("# FairytaleQA -- corpus characterization")
    lines.append("")
    lines.append(f"Generated by `scripts/build_fairytaleqa_stats.py` from "
                  f"`scripts/convert_fairytaleqa.py`'s output "
                  f"({n} episodes, one per (story section(s), question) pair "
                  "of the full 277/278-story fetch -- see "
                  "dev/K12_CORPUS_SCOUT.md and "
                  "data/k12_samples/fairytaleqa_full_sample/MANIFEST.json).")
    lines.append("")

    # -------------------------------------------------------------------
    # 1. counts by split / attribute / explicit-implicit
    # -------------------------------------------------------------------
    lines.append("## Counts")
    lines.append("")
    by_split = Counter(e["meta"]["split"] for e in episodes)
    lines.append("### By split")
    lines.append("")
    for k in ("train", "val", "test"):
        c = by_split.get(k, 0)
        lines.append(f"- {k}: {c} ({_pct(c, n)})")
    other = n - sum(by_split.get(k, 0) for k in ("train", "val", "test"))
    if other:
        lines.append(f"- other/unknown: {other} ({_pct(other, n)})")
    lines.append("")

    by_attr = Counter(e["meta"]["attribute"] for e in episodes)
    lines.append("### By attribute")
    lines.append("")
    for k, c in by_attr.most_common():
        lines.append(f"- {k}: {c} ({_pct(c, n)})")
    lines.append("")

    by_exim = Counter(e["meta"]["ex_or_im"] for e in episodes)
    lines.append("### By explicit/implicit (annotator 1's `ex-or-im1`)")
    lines.append("")
    for k, c in by_exim.most_common():
        lines.append(f"- {k or '(blank)'}: {c} ({_pct(c, n)})")
    lines.append("")

    by_local = Counter(e["meta"]["local_or_sum"] for e in episodes)
    lines.append("### By local-or-summary")
    lines.append("")
    for k, c in by_local.most_common():
        lines.append(f"- {k}: {c} ({_pct(c, n)})")
    lines.append("")

    # -------------------------------------------------------------------
    # 2. passage length distribution
    # -------------------------------------------------------------------
    lines.append("## Passage length distribution")
    lines.append("")
    n_sents = [len(e["context"]) for e in episodes]
    n_tokens = [sum(len(s.split()) for s in e["context"]) for e in episodes]

    def _dist(vals: List[int]) -> str:
        vals_sorted = sorted(vals)
        q = lambda p: vals_sorted[min(len(vals_sorted) - 1, int(p * len(vals_sorted)))]
        return (f"min={min(vals)} p25={q(0.25)} median={statistics.median(vals):.0f} "
                f"p75={q(0.75)} p95={q(0.95)} max={max(vals)} mean={statistics.mean(vals):.1f}")

    lines.append(f"- sentences/passage: {_dist(n_sents)}")
    lines.append(f"- tokens/passage: {_dist(n_tokens)}")
    lines.append("")

    # -------------------------------------------------------------------
    # 3. parse yield over ALL sentences (the big number)
    # -------------------------------------------------------------------
    lines.append("## Parse yield (over every sentence cited by any episode's passage)")
    lines.append("")
    lines.append("Every SECTION in the fetch is parsed exactly once through "
                  "`nsm_ct.corpus.parse_passage` (the real `quantum_parser` "
                  "teacher, default `CORPUS_MAX_HYPOTHESES`/"
                  "`CORPUS_MAX_PARSE_SECONDS` caps, unmodified) and cached; a "
                  "summary question's multi-section passage stats are the "
                  "union of its cited sections' cached per-sentence outcomes "
                  "-- see `scripts/convert_fairytaleqa.py`'s module docstring. "
                  "This table is over the resulting per-SECTION sentence set "
                  "(no double-counting a section shared by multiple "
                  "questions).")
    lines.append("")

    seen_sections = set()
    hist: Counter = Counter()
    total_sents = 0
    for e in episodes:
        key = (e["meta"]["story_id"], tuple(e["meta"]["section_id"]))
        # parse_stats.histogram is a per-EPISODE union of its cited
        # sections; dedup by (story, section-tuple) so a section shared by
        # several questions (the common "local" case) is only counted once.
        if key in seen_sections:
            continue
        seen_sections.add(key)
        ps = e["meta"]["parse_stats"]
        total_sents += ps["n_sentences"]
        for k, v in ps["histogram"].items():
            hist[k] += v

    strict = hist.get("ok", 0)
    usable = strict + hist.get("parsed-ambiguous", 0) + hist.get("parsed-pronoun-resolved", 0)
    cap_hit = hist.get("parse-resource-capped", 0)
    grounding_fail = sum(hist.get(k, 0) for k in _GROUNDING_FAIL_REASONS)
    lines.append(f"**{total_sents} sentences** (deduped by unique (story, section-set) passage):")
    lines.append("")
    lines.append(f"- strict full-tree (`ok`, unambiguous, no pronoun fallback): "
                  f"{strict} ({_pct(strict, total_sents)})")
    lines.append(f"- usable (strict + `parsed-ambiguous` + `parsed-pronoun-resolved` "
                  f"-- at least one real fact extracted): {usable} ({_pct(usable, total_sents)})")
    lines.append(f"- cap-hit (`parse-resource-capped` -- gave up on purpose): "
                  f"{cap_hit} ({_pct(cap_hit, total_sents)})")
    lines.append(f"- grounding-fail (every other failure reason -- no fact extracted, "
                  f"not a resource cap): {grounding_fail} ({_pct(grounding_fail, total_sents)})")
    lines.append("")
    lines.append("Full taxonomy breakdown:")
    lines.append("")
    for k, v in sorted(hist.items(), key=lambda kv: -kv[1]):
        lines.append(f"- {k}: {v} ({_pct(v, total_sents)})")
    lines.append("")

    fully_parseable = sum(1 for e in episodes if e["meta"]["fully_parseable"])
    lines.append(f"**Episode-level**: {fully_parseable}/{n} episodes ({_pct(fully_parseable, n)}) "
                  "have EVERY sentence of their passage land in a usable outcome "
                  "(`ok`/`parsed-ambiguous`/`parsed-pronoun-resolved`) -- i.e. fully "
                  "parseable end to end by today's teacher.")
    lines.append("")

    # -------------------------------------------------------------------
    # 4. answer-type breakdown
    # -------------------------------------------------------------------
    lines.append("## Answer-type breakdown")
    lines.append("")
    lines.append("NAOMI's current QA head answers with a single entity/value "
                  "(MC over content-word options) -- (a) is scorable TODAY; "
                  "(b)-(d) need the realization side (free-text generation) "
                  "before they're scorable at all. See "
                  "`scripts/convert_fairytaleqa.py::classify_answer_type`.")
    lines.append("")
    by_atype = Counter(e["meta"]["answer_type"] for e in episodes)
    labels = {
        "entity": "(a) single entity/noun phrase, verbatim in the passage",
        "verb_phrase": "(b) verb phrase / action",
        "free_text": "(c) free-text sentence",
        "not_substring": "(d) not a substring of the passage at all",
    }
    for k in ("entity", "verb_phrase", "free_text", "not_substring"):
        c = by_atype.get(k, 0)
        lines.append(f"- {labels[k]}: {c} ({_pct(c, n)})")
    lines.append("")
    n_with_options = sum(1 for e in episodes if e.get("options"))
    lines.append(f"Of the {by_atype.get('entity', 0)} entity-type episodes, "
                  f"{n_with_options} ({_pct(n_with_options, max(by_atype.get('entity', 0), 1))} "
                  "of entity-type) got >=2 same-attribute MC distractors and are "
                  "MC-scoreable (`--answer-type entity` hook, "
                  "`scripts/eval_prose.py`).")
    lines.append("")

    # -------------------------------------------------------------------
    # 5. examples per attribute
    # -------------------------------------------------------------------
    lines.append("## Example questions per attribute (10 each)")
    lines.append("")
    by_attr_examples: Dict[str, List[dict]] = defaultdict(list)
    for e in episodes:
        a = e["meta"]["attribute"]
        if len(by_attr_examples[a]) < 10:
            by_attr_examples[a].append(e)
    for attr in sorted(by_attr_examples):
        lines.append(f"### {attr}")
        lines.append("")
        for e in by_attr_examples[attr]:
            lines.append(f"- Q: {e['question']} -- A: {e['answer_text']!r} "
                          f"(`{e['meta']['story_id']}`, {e['meta']['ex_or_im']}, "
                          f"{e['meta']['answer_type']})")
        lines.append("")

    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--episodes", type=Path, default=_ROOT / "runs" / "fairytaleqa_episodes.jsonl")
    ap.add_argument("--out", type=Path, default=_ROOT / "dev" / "FAIRYTALEQA_STATS.md")
    args = ap.parse_args()

    episodes = load_episodes(args.episodes)
    if not episodes:
        raise SystemExit(f"no episodes loaded from {args.episodes}")
    doc = build(episodes)
    args.out.write_text(doc, encoding="utf-8")
    print(f"wrote {args.out} ({len(episodes)} episodes)")


if __name__ == "__main__":
    main()
