"""DeepNSM Explication Store for the NSM Consciousness Transformer.

Loads the DeepNSM corpus (baartmar/nsm_dataset, arxiv 2505.11764) and makes
explications available for the meaning resolver.

PROVENANCE: All explications in the DeepNSM corpus are AI-GENERATED by
Gemini-2.0-Flash as described in arxiv 2505.11764. They are NOT gold-standard
literature explications. Provenance strings are always prefixed ``ai_generated``
to make this unambiguous. Gold / literature explications, if provided via a
separate gold file, are labeled ``gold:literature``.

Attribution: baartmar/nsm_dataset, CC BY-NC-SA 4.0. See NOTICE.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Optional

from .data_structures import ParseNode, ParseTree

# Default paths (resolved relative to this file's repo location)
# explications.py lives at: <repo>/src/nsm_ct/explications.py
# .parent -> nsm_ct/, .parent.parent -> src/, .parent.parent.parent -> <repo>/
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_DEFAULT_JSONL = _REPO_ROOT / "data" / "deepnsm_explications.jsonl"
_DEFAULT_GOLD = _REPO_ROOT / "data" / "gold_explications.json"


def _build_prime_exponent_map() -> Dict[str, str]:
    """Build a map from every prime exponent (lower-case) to its prime name."""
    from .nsm_primes import PRIMES

    mapping: Dict[str, str] = {}
    for prime in PRIMES:
        parts = prime.exponent.split("~")
        for part in parts:
            bare = part.split("(")[0].strip().lower()
            if bare:
                mapping[bare] = prime.name
    return mapping


def _build_molecule_exponent_map() -> Dict[str, str]:
    """Build a map from every molecule exponent (lower-case) to its molecule name."""
    from .nsm_molecules import MOLECULES_BY_EXPONENT

    return {exp.lower(): mol.name for exp, mol in MOLECULES_BY_EXPONENT.items()}


class ExplicationStore:
    """A lookup store mapping words (and synset ids) to NSM explications.

    Two layers:
    1. **Gold** (literature) entries — loaded from an optional JSON file. Each
       entry is ``{"word": str, "explication": str, "source": str}``. Gold takes
       precedence over DeepNSM for the same word.
    2. **DeepNSM** (AI-generated) entries — loaded from the JSONL corpus. Among
       multiple DeepNSM rows for the same word the resolver prefers test-split
       rows (hand-refined) and then highest score.

    All DeepNSM provenance strings carry the ``ai_generated`` prefix and the
    CC BY-NC-SA 4.0 attribution. Gold provenance strings carry ``gold:literature``.
    """

    def __init__(self) -> None:
        # word.lower() -> {"explication": str, "provenance": str, "score": float|None}
        self._gold: Dict[str, dict] = {}
        # word.lower() -> best DeepNSM row {"explication": str, "provenance": str, "score": float|None}
        self._deepnsm: Dict[str, dict] = {}
        # syn -> same structure (DeepNSM only; gold rarely carries synset ids)
        self._deepnsm_syn: Dict[str, dict] = {}

    # ------------------------------------------------------------------
    # Loading
    # ------------------------------------------------------------------

    @classmethod
    def load(
        cls,
        path: Optional[str | Path] = None,
        gold_path: Optional[str | Path] = None,
    ) -> "ExplicationStore":
        """Load the explication store from disk.

        Args:
            path: Path to the DeepNSM JSONL file. Defaults to
                ``consciousness_transformer/data/deepnsm_explications.jsonl``.
                Missing file is silently ignored (store stays empty).
            gold_path: Path to gold JSON file. Defaults to
                ``consciousness_transformer/data/gold_explications.json``.
                Missing file is silently ignored.

        Returns:
            A populated :class:`ExplicationStore`.
        """
        store = cls()

        # Load gold first (takes precedence)
        gpath = Path(gold_path) if gold_path is not None else _DEFAULT_GOLD
        if gpath.exists():
            store._load_gold(gpath)

        # Load DeepNSM JSONL
        dpath = Path(path) if path is not None else _DEFAULT_JSONL
        if dpath.exists():
            store._load_deepnsm(dpath)

        return store

    def _load_gold(self, path: Path) -> None:
        """Load gold entries from a JSON list file."""
        try:
            with open(path, encoding="utf-8") as fh:
                entries = json.load(fh)
            for entry in entries:
                word = entry.get("word", "").strip().lower()
                explication = entry.get("explication", "").strip()
                source = entry.get("source", "unknown")
                if word and explication:
                    self._gold[word] = {
                        "explication": explication,
                        "provenance": f"gold:literature ({source})",
                        "score": None,
                    }
        except Exception:
            pass  # graceful: malformed gold file is ignored

    def _load_deepnsm(self, path: Path) -> None:
        """Load DeepNSM JSONL, keeping best row per word (test > score)."""
        # _best: word.lower() -> (priority_key, row_dict)
        # priority_key: (split_rank, score) — lower split_rank is better,
        # higher score is better (we negate score for min-heap analogy).
        _SPLIT_RANK = {"test": 0, "validation": 1, "train": 2}

        best: Dict[str, tuple] = {}  # word -> (split_rank, neg_score, row_dict)
        best_syn: Dict[str, tuple] = {}  # syn -> same

        try:
            with open(path, encoding="utf-8") as fh:
                for line in fh:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        obj = json.loads(line)
                    except json.JSONDecodeError:
                        continue

                    word = (obj.get("word") or "").strip().lower()
                    syn = (obj.get("syn") or "").strip()
                    explication = (obj.get("explication") or "").strip()
                    score = obj.get("score")
                    split = (obj.get("split") or "train").strip()

                    if not word or not explication:
                        continue

                    split_rank = _SPLIT_RANK.get(split, 2)
                    neg_score = -(score if isinstance(score, (int, float)) else 0.0)
                    priority = (split_rank, neg_score)

                    if split == "test":
                        prov = "ai_generated:DeepNSM hand-refined (Gemini, cc-by-nc-sa-4.0)"
                    else:
                        prov = "ai_generated:DeepNSM (Gemini, cc-by-nc-sa-4.0)"

                    row = {
                        "explication": explication,
                        "provenance": prov,
                        "score": score,
                    }

                    if word not in best or priority < best[word][0]:
                        best[word] = (priority, row)

                    if syn and (syn not in best_syn or priority < best_syn[syn][0]):
                        best_syn[syn] = (priority, row)

        except Exception:
            pass  # graceful: missing or corrupted file -> empty store

        self._deepnsm = {w: v[1] for w, v in best.items()}
        self._deepnsm_syn = {s: v[1] for s, v in best_syn.items()}

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def get(self, word: str) -> Optional[dict]:
        """Look up an explication by word or synset id.

        Precedence:
        1. Gold (literature) — exact lower-case word match.
        2. DeepNSM by word (test-split preferred, then highest score).
        3. DeepNSM by synset id (when ``word`` looks like a WN synset).

        Returns:
            A dict ``{"explication": str, "provenance": str, "score": float|None}``
            or ``None`` if not found.
        """
        key = word.strip().lower()

        # 1. Gold
        if key in self._gold:
            return self._gold[key]

        # 2. DeepNSM by word
        if key in self._deepnsm:
            return self._deepnsm[key]

        # 3. DeepNSM by synset (if the key looks like a synset id, e.g. "snake.n.01")
        if key in self._deepnsm_syn:
            return self._deepnsm_syn[key]

        return None

    def __len__(self) -> int:
        """Total number of unique words across gold and DeepNSM."""
        return len(self._gold) + len(self._deepnsm)

    def is_empty(self) -> bool:
        """True when neither gold nor DeepNSM has any entries."""
        return len(self._gold) == 0 and len(self._deepnsm) == 0

    # ------------------------------------------------------------------
    # Tree conversion
    # ------------------------------------------------------------------

    def explication_to_tree(self, text: str) -> ParseTree:
        """Convert an NSM explication prose string to a flat ParseTree.

        Tokenizes ``text`` using :func:`nsm_ct.tokenizer.basic_tokenize` and maps
        each token to the corresponding NSM prime or molecule name. Unmatched
        tokens are silently skipped. The result is a flat tree: a generic
        ``"EXPLICATION"`` root node with one child per matched prime/molecule
        token (in order of first occurrence).

        The tree is suitable for passing to
        :func:`nsm_ct.thought.meaning_prime_ids` which flattens node labels to
        prime-id bags.

        Args:
            text: An NSM Minimal-English explication string (free prose).

        Returns:
            A :class:`~nsm_ct.data_structures.ParseTree` with root label
            ``"EXPLICATION"`` and children whose labels are canonical prime or
            molecule names.
        """
        from .tokenizer import basic_tokenize  # local import

        # Build lookup maps lazily (cached as class-level attributes)
        prime_map = _build_prime_exponent_map()
        mol_map = _build_molecule_exponent_map()

        tokens = basic_tokenize(text)
        root = ParseNode(label="EXPLICATION")
        seen: set = set()

        for tok in tokens:
            # Try prime first, then molecule
            label: Optional[str] = prime_map.get(tok)
            if label is None:
                label = mol_map.get(tok)
            if label is not None and label not in seen:
                root.children.append(ParseNode(label=label))
                seen.add(label)

        return ParseTree(root=root, text=text)
